#!/bin/bash

_set_bot () {
   # local zippath
    zippath="catuserbot.zip"
    echo "  Downloading source code ..."
   # wget -q https://ankitkumarbh:250298gh@github.com/ankitkumarbh/Tele-Bot/archive/master.zip -O "$zippath"
    git clone https://github.com/ankitkumarbh/Black-Lightning userbot
    echo "  Unpacking Data ..."
   # CATPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
   # unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
   # rm -rf "$zippath"
    sleep 5
   # cd $CATPATH
    cd userbot
    chmod -R 755 bin
    echo "    Starting CatUserBot    "
    echo "
                        :'######:::::'###::::'########::::
                        '##... ##:::'## ##:::... ##..:::::
                         ##:::..:::'##:. ##::::: ##:::::::
                         ##:::::::'##:::. ##:::: ##:::::::
                         ##::::::: #########:::: ##:::::::
                         ##::: ##: ##.... ##:::: ##:::::::
                        . ######:: ##:::: ##:::: ##:::::::
                        :......:::..:::::..:::::..::::::::
    "

    echo "
    '##::::'##::'######::'########:'########::'########:::'#######::'########:
     ##:::: ##:'##... ##: ##.....:: ##.... ##: ##.... ##:'##.... ##:... ##..::
     ##:::: ##: ##:::..:: ##::::::: ##:::: ##: ##:::: ##: ##:::: ##:::: ##::::
     ##:::: ##:. ######:: ######::: ########:: ########:: ##:::: ##:::: ##::::
     ##:::: ##::..... ##: ##...:::: ##.. ##::: ##.... ##: ##:::: ##:::: ##::::
     ##:::: ##:'##::: ##: ##::::::: ##::. ##:: ##:::: ##: ##:::: ##:::: ##::::
    . #######::. ######:: ########: ##:::. ##: ########::. #######::::: ##::::
    :.......::::......:::........::..:::::..::........::::.......::::::..:::::
    "
   # python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
